server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:3000"
              - "http://localhost:4200"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

  eureka:
    client:
      enabled: false
