server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: auth-service
              uri: http://localhost:8083
              predicates:
                - Path=/auth/**
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "http://localhost:3000"
                  - "http://localhost:4200"
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true
